name: Build artifacts
run-name: Build on '${{ github.ref_name }}' branch push (${{ github.event.head_commit.message }})

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '.github/**'
      - 'docs/**'
      - '**.md'

concurrency:
  group: build-branch-${{ github.ref_name }}
  cancel-in-progress: true

jobs:

  validate:
    name: Check
    uses: ./.github/workflows/sub-check.yml

  metadata:
    name: Meta
    uses: ./.github/workflows/sub-metadata.yml

  docker:
    name: Build
    needs: [validate, metadata]
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/sub-build-docker.yml
    with:
      REGISTRY_IMAGE: ${{ vars.REGISTRY_IMAGE || 'berkut174/webtlo' }}
      WEBTLO_VERSION: ${{ needs.metadata.outputs.version }}
      WEBTLO_SHA: ${{ needs.metadata.outputs.sha }}
      GHCR_ONLY: true

  zip:
    name: Build
    needs: [validate, metadata]
    uses: ./.github/workflows/sub-build-zip.yml
    with:
      WEBTLO_VERSION: ${{ needs.metadata.outputs.version }}
      WEBTLO_SHA: ${{ needs.metadata.outputs.sha }}
